verbose: false
instrumentation:
  root: ./src
  default-excludes: true
  excludes: ['**/__test__/**']
  embed-source: false
  variable: __coverage__
  compact: true
  preserve-comments: false
  complete-copy: false
  save-baseline: false
  baseline-file: ./coverage/coverage-baseline.json
reporting:
  print: summary
  reports:
    - lcov
  dir: ./coverage
  watermarks:
    statements: [80, 90]
    lines: [80, 90]
    functions: [80, 90]
    branches: [80, 90]
hooks:
  hook-run-in-context: false
  post-require-hook: null
  handle-sigint: false
